CREATE DATABASE shopping_project;
USE shopping_project;

SELECT * FROM customer LIMIT 10;

SHOW TABLES;
SELECT * FROM 	customer LIMIT 10;


-- Q1 What is the total revenue generated by male vs female customers?
SELECT gender,sum(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2 Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = "Yes"
AND purchase_amount >= (
	SELECT AVG(purchase_amount) 
    FROM customer
);

-- Q3 Which 5 products have the highest average review rating?
SELECT item_purchased,round(AVG(review_rating),2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating
LIMIT 10;

-- Q4 Compare average purchase amounts between Standard and Express shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5 Subscriber vs Non-subscriber spending comparison
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6 Products with highest percentage of discount purchases
SELECT item_purchased,
       ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Customer segmentation based on previous purchases
SELECT 
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS number_of_customers
FROM customer
GROUP BY customer_segment;

-- Q8 Top 3 products within each category
SELECT *FROM (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER(
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
) ranked_products
WHERE rank_in_category <= 3;

-- Q9 Subscription status of repeat buyers
SELECT subscription_status,COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 Revenue contribution by age group
SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
